# ----- Serveur -----
    ##Lance le server web intégré TOMCat sur le port 8080
#server.port=8080

# ----- H2 (Base de données mémoire) -----
    ##Adresse de la base de données H2/en mémoire/nom:annuairedb/ne se ferme pa automatiquement à la fin d'une requête
#spring.datasource.url=jdbc:h2:mem:annuairedb;DB_CLOSE_DELAY=-1
    ##Indique le nom du driver H2
pring.datasource.driverClassName=org.h2.Driver
    ##Nom d'utilisateur par défaut:sa(system administrator)
spring.datasource.username=sa
    ##Pas besoin de mot de passe
spring.datasource.password=
    ##Active la console web H2(interface graphique dans le navigateur)
spring.h2.console.enabled=true
    ##Chemin URL pour couvrir la console H2
spring.h2.console.path=/h2-console

# ----- JPA / Hibernate -----
    ##JPA indique à Hibernate comment gérer les tables en BD
#spring.jpa.hibernate.ddl-auto=update
    ##Affiche toutes les requêtes SQL générées par Hibernate dans la console
#spring.jpa.show-sql=true
    ##Rendre les requêtes SQL beaucoup plus lisible dans la console (mise en forme)
#spring.jpa.properties.hibernate.format_sql=true
